name: Build, Test, and Tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff check
        run: poetry run ruff check
      
      - name: Run Pytest with coverage
        run: poetry run pytest --cov=r82labs_analytics --cov-report=term

      - name: Fail if coverage < 100%
        run: |
          coverage=$(poetry run coverage report | grep 'TOTAL' | awk '{print $4}' | tr -d '%')
          if [ "$coverage" -lt 100 ]; then
            echo "Test coverage is less than 100% ($coverage%)"
            exit 1
          fi

      - name: Get project version
        id: get_version
        run: |
          version=$(poetry version -s)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set tag version
        id: set_tag_version
        run: |
          tag="v${{ steps.get_version.outputs.version }}"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create and push tag if version updated
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.set_tag_version.outputs.tag }}"
          git fetch --tags
          if git tag --list | grep -q "^$tag$"; then
            echo "Tag $tag already exists. Skipping tag creation."
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$tag"
          git push origin "$tag"

      - name: Run poetry build
        run: poetry build
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag_version.outputs.tag }}
          name: Release ${{ steps.set_tag_version.outputs.tag }}
          body: |
            ## Release Notes
            This is the release for tag ${{ steps.set_tag_version.outputs.tag }}. See commit history for detailed changes.
          files: |
            dist/r82labs_analytics-*.tar.gz
          draft: false
          prerelease: false
