name: Build, Test, and Tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Ruff check
        run: poetry run ruff check
      
      - name: Run Pytest with coverage
        run: poetry run pytest --cov=r82labs_analytics --cov-report=term

      - name: Fail if coverage < 100%
        run: |
          coverage=$(poetry run coverage report | grep 'TOTAL' | awk '{print $4}' | tr -d '%')
          if [ "$coverage" -lt 100 ]; then
            echo "Test coverage is less than 100% ($coverage%)"
            exit 1
          fi

      - name: Get project version
        id: get_version
        run: |
          version=$(poetry version -s)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set tag version
        id: set_tag_version
        run: |
          tag="v${{ steps.get_version.outputs.version }}"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create and push tag if version updated
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.set_tag_version.outputs.tag }}"
          git fetch --tags
          if git tag --list | grep -q "^$tag$"; then
            echo "Tag $tag already exists. Skipping tag creation."
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$tag"
          git push origin "$tag"

      - name: Run poetry build
        run: poetry build
      
      - name: Check if release exists
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.set_tag_version.outputs.tag }}"
          release_url="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/$tag"
          status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_TOKEN" "$release_url")
          if [ "$status" -eq 200 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ steps.set_tag_version.outputs.tag }}
         release_name: Release ${{ steps.set_tag_version.outputs.tag }}
         body: |
           ## Release Notes
           This is the release for tag ${{ steps.set_tag_version.outputs.tag }}. See commit history for detailed changes.
         draft: false
         prerelease: false

      - name: Upload Release Asset
        if: steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/r82labs_analytics-${{ steps.get_version.outputs.version }}.tar.gz
          asset_name: r82labs-analytics-${{ steps.set_tag_version.outputs.tag }}.tar.gz
          asset_content_type: application/gzip