name: Build and Deploy Docs

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs-actions.yml'
  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: poetry install --with docs

      - name: Sphinx build
        run: |
         cd docs
         poetry run make html
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: docs/build/html
         publish_branch: gh-pages