name: Main Branch Actions

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test-actions.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set tag version
        id: set_tag_version
        run: |
          tag="v$(poetry version -s)"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        uses: actions/github-script@v7
        id: tag_push
        if: github.ref == 'refs/heads/main'
        with:
          script: |
            const tag = '${{ steps.set_tag_version.outputs.tag }}';
            
            try {
              await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag,
              });
              core.info(`Tag ${tag} already exists. Skipping tag creation.`);
              return;
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }
            
            core.info(`Creating and pushing tag ${tag}...`);
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha, // Tag at the current commit SHA
            });
            
            core.setOutput('tag_created', 'true');
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run poetry build
        if: steps.tag_push.outputs.tag_created == 'true'
        run: poetry build
      
      - name: Create Release and Upload Asset
        if: steps.tag_push.outputs.tag_created == 'true'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag_version.outputs.tag }}
          name: Release ${{ steps.set_tag_version.outputs.tag }}
          body: |
            ## Release Notes
            This is the release for tag ${{ steps.set_tag_version.outputs.tag }}. See commit history for detailed changes.
          files: |
            dist/r82labs_analytics-*.tar.gz
          draft: false
          prerelease: false
